version: '3'
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    networks:
      - app-network
    environment:
      - MPLCONFIGDIR=/tmp

networks:
  app-network:
    driver: bridge
volumes:
  sqlite_data:
    driver: local
